// ─── WC26 EDGE · Complete Fixture Data ────────────────────────────
// Updated: 24 June 2026 — starts from Wed 24, Tue 23 completed

export const DATES = [
  { day: 'WED', num: 24, key: '24', cnt: 6, hot: true, today: true },
  { day: 'THU', num: 25, key: '25', cnt: 6, hot: true },
  { day: 'FRI', num: 26, key: '26', cnt: 6, hot: false },
  { day: 'SAT', num: 27, key: '27', cnt: 6, hot: true },
  { day: 'SUN', num: 28, key: '28', cnt: 8, hot: true, r32: true },
];

// ─── PLAYER IMPACT DATABASE ──────────────────────────────────────
export const PLAYER_IMPACT = {
  'Cristiano Ronaldo':  { oddsShift: { h: -30, a: 50  }, confBoost: 3, props: ['SOT+15%', 'scorer+10%'] },
  'Harry Kane':         { oddsShift: { h: -20, a: 35  }, confBoost: 2, props: ['SOT+12%', 'corners+1'] },
  'Kylian Mbappé':      { oddsShift: { h: -25, a: 40  }, confBoost: 3, props: ['SOT+14%', 'scorer+12%'] },
  'Erling Haaland':     { oddsShift: { h: -20, a: 30  }, confBoost: 2, props: ['SOT+18%', 'scorer+15%'] },
  'Declan Rice':        { oddsShift: { h: -10, a: 15  }, confBoost: 1, props: ['fouls+95%', 'cards+8%'] },
  'Vinícius Jr':        { oddsShift: { a: -15, h: 25  }, confBoost: 2, props: ['SOT+10%', 'corners+2'] },
  'Lamine Yamal':       { oddsShift: { a: -18, h: 28  }, confBoost: 2, props: ['SOT+12%', 'corners+1'] },
  'Kaoru Mitoma':       { oddsShift: { h: 20,  a: -12 }, confBoost: -2, props: ['INJURED OUT — SOT-15%'] },
  'Memphis Depay':      { oddsShift: { h: -20, a: 35  }, confBoost: 3, props: ['SOT+15%', 'scorer+12%'] },
  'Alexander Isak':     { oddsShift: { a: -18, h: 25  }, confBoost: 2, props: ['SOT+14%', 'scorer+10%'] },
  'Viktor Gyökeres':    { oddsShift: { a: -10, h: 15  }, confBoost: 1, props: ['fouls+92%', 'scorer+8%'] },
  'Mohamed Salah':      { oddsShift: { h: -20, a: 30  }, confBoost: 2, props: ['SOT+12%', 'corners+1'] },
  'Rúben Neves':        { oddsShift: { h: -8,  a: 12  }, confBoost: 1, props: ['fouls+95%'] },
  'Ryan Gravenberch':   { oddsShift: { h: -10, a: 18  }, confBoost: 1, props: ['fouls+96%'] },
  'Frenkie de Jong':    { oddsShift: { h: -8,  a: 12  }, confBoost: 1, props: ['fouls+88%', 'card+12%'] },
  'Granit Xhaka':       { oddsShift: { h: -8,  a: 12  }, confBoost: 1, props: ['fouls+89%', 'card+10%'] },
  'Thomas Partey':      { oddsShift: { a: 8,   h: -5  }, confBoost: 1, props: ['fouls+82%'] },
  'Casemiro':           { oddsShift: { a: -10, h: 15  }, confBoost: 1, props: ['fouls+91%', 'card+8%'] },
  'Wataru Endo':        { oddsShift: { h: 5,   a: -5  }, confBoost: 0, props: ['fouls+82%'] },
};

// ─── FIXTURE BUILDERS ────────────────────────────────────────────
const foul = (name, club, hot, hitClass, hitTag, stats, dots, conf, bets, note) =>
  ({ name, club, hot, hitClass, hitTag, stats, dots, conf, bets, note });

const shot = (name, club, hot, hitClass, hitTag, stats, sdots, sotdots, shotHit, sotHit, bets) =>
  ({ name, club, hot, hitClass, hitTag, stats, sdots, sotdots, shotHit, sotHit, bets });

const easy = (cat, pick, odds, conf, star) => ({ cat, pick, odds, conf, star });
const leg  = (pick, odds) => ({ pick, odds });

// ─── DAYS DATA ───────────────────────────────────────────────────
export const DAYS = {

  '24': {
    title: 'Wednesday 24 June 2026',
    sub: 'MD3 · Groups A B C · 6 matches · 2 LIVE now (3pm ET) · 2 at 6pm · 2 at 9pm',
    matches: [

      // ── GROUP B 3pm ET LIVE ──────────────────────────────────
      {
        id: 'swi_can', live: true, liveScore: '● LIVE',
        teams: '🇨🇭 Switzerland vs Canada 🇨🇦',
        group: 'Group B', venue: 'Vancouver · BC Place', time: '3pm ET / 8pm BST',
        tag: 'upset', tagLabel: '⚠ Tight 56/44',
        conf: 56, upset: 44,
        odds: { h: '-160', d: '+300', a: '+420', ou: '2.5' },
        homeTeam: 'Switzerland', awayTeam: 'Canada', winner: 'Switzerland',
        wP: 56, dP: 25, aP: 19,
        keyPlayers: { home: ['Granit Xhaka'], away: ['Alphonso Davies'] },
        confBars: [
          { label: 'Switzerland win', pct: 56, color: '#f59e0b' },
          { label: 'Canada upset (won 6-0 in MD2)', pct: 44, color: '#ef4444' },
          { label: 'Xhaka 1+ fouls (100% L10)', pct: 89, color: '#00c896' },
          { label: 'Over 2.5 goals', pct: 68, color: '#f59e0b' },
        ],
        fouls: [
          foul('Granit Xhaka', 'Leverkusen · Switzerland · CM', true, 'h100', '100% last 10',
            [['Fouls/90 BL', '1.6/g'], ['YC BL 25/26', '9'], ['vs Canada press', 'Physical battle']],
            [1,1,1,1,1,1,1,1,1,1], 89,
            [{ label: 'Xhaka 1+ fouls committed', odds: ['-155 bet365', '-145 FanDuel'] }, { label: 'Xhaka to be booked', odds: ['+175 est. Paddy'] }],
            '1.6 fouls/90 all season. 100% last 10. Canada high-energy attack forces repeated fouling — near certainty.'),
        ],
        shots: [
          shot('Alphonso Davies', 'Bayern Munich · Canada · LW/LB', false, 'h80', '80% last 10',
            [['Shots/90 BL', '1.9'], ['Dribbles/g', '3.2'], ['MD2 result', 'Won 6-0 Qatar']],
            [1,1,1,1,0,1,1,0,1,1], [1,0,1,1,0,1,1,1,0,1], 76, 62,
            [{ label: 'Davies 1+ SOT', odds: ['-120 est.'] }]),
        ],
        easy: [
          easy('Fouls ★', 'Xhaka 1+ fouls committed', '-155 bet365', 89, true),
          easy('Goals', 'Over 2.5 goals', '+115 est.', 68, false),
          easy('Throw-ins', 'Over 42 total throw-ins', '-110 est.', 74, true),
          easy('Corners', 'Over 9 total corners', '+100 est.', 63, false),
          easy('Live edge', 'Canada win if they score first', 'Live odds', 71, true),
        ],
        parlay: [leg('Xhaka 1+ fouls', '-155'), leg('Over 2.5 goals', '+115'), leg('Davies 1+ SOT', '-120')],
        parlayReturn: '+170–200',
        upsetNote: 'Canada beat Qatar 6-0 in MD2 — red-hot form. 44% upset. Canada have conceded in both earlier games — live bet opportunity if they score first.',
        ai: 'Switzerland (-160) vs Canada (+420, won MD2 6-0 Qatar). LIVE NOW. Xhaka: 1.6 fouls/90, 100% last 10. Davies: 1.9 shots/90. WC2026 avg corners 10.6, throw-ins 46, fouls 24.4.',
      },

      {
        id: 'bos_qat', live: true, liveScore: '● LIVE',
        teams: '🇧🇦 Bosnia & Herz. vs Qatar 🇶🇦',
        group: 'Group B', venue: 'Seattle · Lumen Field', time: '3pm ET / 8pm BST',
        tag: 'info', tagLabel: '65% Bosnia',
        conf: 65, upset: 35,
        odds: { h: '-270', d: '+420', a: '+650', ou: '2.5' },
        homeTeam: 'Bosnia & Herz.', awayTeam: 'Qatar', winner: 'Bosnia & Herz.',
        wP: 65, dP: 21, aP: 14,
        keyPlayers: { home: ['Edin Džeko', 'Amar Dedić'], away: [] },
        confBars: [
          { label: 'Bosnia & Herz. win', pct: 65, color: '#f59e0b' },
          { label: 'Qatar effectively eliminated', pct: 95, color: '#00c896' },
          { label: 'Over 2.5 goals', pct: 62, color: '#f59e0b' },
        ],
        fouls: [
          foul('Amar Dedić', 'RB Salzburg · Bosnia · RB', false, 'h90', '90% last 10',
            [['Fouls/90', '1.1'], ['Role', 'Aggressive RB'], ['YC/season', '5']],
            [1,1,1,0,1,1,1,1,1,1], 74,
            [{ label: 'Dedić 1+ fouls', odds: ['-125 est.'] }],
            'Bosnia full-back who fouls to prevent Qatar counterattacks. 90% last 10.'),
        ],
        shots: [
          shot('Edin Džeko', 'Fenerbahçe · Bosnia · ST', false, 'h90', '90% last 10',
            [['Shots/90', '2.1'], ['SOT/game', '0.9'], ['Career WC goals', '3']],
            [1,1,1,1,1,0,1,1,1,1], [1,1,0,1,1,1,0,1,1,1], 80, 65,
            [{ label: 'Džeko 1+ SOT', odds: ['-120 est.'] }]),
        ],
        easy: [
          easy('Goals', 'Over 2.5 goals', '+115 est.', 62, false),
          easy('Throw-ins', 'Over 40 total throw-ins', '-110 est.', 72, true),
          easy('Result', 'Bosnia & Herz. win', '-270 est.', 65, false),
        ],
        parlay: [leg('Dedić 1+ fouls', '-125'), leg('Over 2.5 goals', '+115')],
        parlayReturn: '+115–140',
        upsetNote: 'Qatar are effectively eliminated. Bosnia need points — desperation can backfire. 35% Qatar shock risk.',
        ai: 'Bosnia (-270) vs Qatar (+650, eliminated). LIVE NOW. Džeko: 2.1 shots/90. Dedić: 90% fouls L10. WC2026 avg fouls 24.4.',
      },

      // ── GROUP C 6pm ET ───────────────────────────────────────
      {
        id: 'sco_bra', live: false, liveScore: null,
        teams: '🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland vs Brazil 🇧🇷',
        group: 'Group C', venue: 'Miami · Hard Rock Stadium', time: '6pm ET / 11pm BST',
        tag: 'top', tagLabel: '★ 89% — best pick',
        conf: 89, upset: 8,
        odds: { h: '+1600', d: '+750', a: '-600', ou: '2.5' },
        homeTeam: 'Scotland', awayTeam: 'Brazil', winner: 'Brazil',
        wP: 4, dP: 7, aP: 89,
        keyPlayers: { home: [], away: ['Vinícius Jr', 'Casemiro', 'Rodrygo'] },
        confBars: [
          { label: 'Brazil win', pct: 89, color: '#00c896' },
          { label: 'Brazil over 2.5 goals', pct: 84, color: '#00c896' },
          { label: 'Vinicius Jr 2+ SOT', pct: 82, color: '#3b82f6' },
          { label: 'Casemiro 1+ fouls (100% L10)', pct: 91, color: '#00c896' },
          { label: 'Brazil 8+ corners', pct: 82, color: '#a855f7' },
        ],
        fouls: [
          foul('Casemiro', 'Man Utd · Brazil · DM', true, 'h100', '100% last 10',
            [['Fouls/90 PL', '1.5'], ['YC/season', '8'], ['vs Scotland press', 'Break aggressively']],
            [1,1,1,1,1,1,1,1,1,1], 91,
            [{ label: 'Casemiro 1+ fouls', odds: ['-160 bet365', '-150 FanDuel'] }, { label: 'Casemiro booked', odds: ['+185 Paddy'] }],
            'Brazil DM enforcer. 100% last 10 — Scotland press hard and Casemiro responds with deliberate challenges every game.'),
        ],
        shots: [
          shot('Vinícius Jr', 'Real Madrid · Brazil · LW', true, 'h100', '100% last 10',
            [['Shots/90 LL', '2.73'], ['SOT/game', '1.5'], ['Goals 25/26', '16 in 32']],
            [1,1,1,1,1,1,1,1,1,1], [1,1,1,1,1,0,1,1,1,1], 95, 82,
            [{ label: 'Vinicius 2+ SOT', odds: ['-145 est.'] }, { label: 'Vinicius anytime scorer', odds: ['-165 FanDuel'] }]),
          shot('Rodrygo', 'Real Madrid · Brazil · RW', false, 'h90', '90% last 10',
            [['Shots/90 LL', '2.1'], ['SOT/game', '1.0'], ['Goals 25/26', '12']],
            [1,1,1,1,1,0,1,1,1,1], [1,1,0,1,1,1,1,0,1,1], 82, 68,
            [{ label: 'Rodrygo 1+ SOT', odds: ['-125 est.'] }]),
        ],
        easy: [
          easy('Goals', 'Brazil over 2.5 goals', '-150 FanDuel', 84, true),
          easy('SOT prop', 'Vinicius 2+ SOT', '-145 est.', 82, true),
          easy('Fouls ★', 'Casemiro 1+ fouls', '-160 bet365', 91, true),
          easy('Corners', 'Brazil 8+ corners', '-130 bet365', 82, true),
          easy('Throw-ins', 'Over 44 total throw-ins', '-120 est.', 79, true),
          easy('Shots', 'Brazil over 17 total shots', '-130 est.', 83, true),
        ],
        parlay: [leg('Casemiro 1+ fouls', '-160'), leg('Vinicius 2+ SOT', '-145'), leg('Brazil over 2.5 goals', '-150'), leg('Brazil 8+ corners', '-130')],
        parlayReturn: '+200–240',
        upsetNote: 'Brazil drew 1-1 Morocco in MD1. Scotland must win to survive. Only 8% upset — strongest banker of the week.',
        refNote: '📋 Brazil avg 10+ corners vs weaker sides. Throw-ins over 44 virtually guaranteed vs Scotland press style.',
        ai: 'Brazil (-600, won MD2 3-0 Haiti) vs Scotland (must win to survive). Vinicius: 2.73 shots/90. Casemiro: 1.5 fouls/90, 100% last 10. WC2026 avg corners 10.6, throw-ins 46.',
      },

      {
        id: 'mor_hai', live: false, liveScore: null,
        teams: '🇲🇦 Morocco vs Haiti 🇭🇹',
        group: 'Group C', venue: 'Atlanta · Mercedes-Benz Stadium', time: '6pm ET / 11pm BST',
        tag: 'top', tagLabel: '★ 87% Morocco',
        conf: 87, upset: 10,
        odds: { h: '-700', d: '+800', a: '+1800', ou: '2.5' },
        homeTeam: 'Morocco', awayTeam: 'Haiti', winner: 'Morocco',
        wP: 87, dP: 9, aP: 4,
        keyPlayers: { home: ['Sofyan Amrabat', 'Hakim Ziyech'], away: [] },
        confBars: [
          { label: 'Morocco win', pct: 87, color: '#00c896' },
          { label: 'Morocco over 2.5 goals', pct: 81, color: '#00c896' },
          { label: 'Amrabat 1+ fouls (100% L10)', pct: 90, color: '#00c896' },
          { label: 'Morocco 8+ corners', pct: 78, color: '#a855f7' },
        ],
        fouls: [
          foul('Sofyan Amrabat', 'Fiorentina · Morocco · DM', true, 'h100', '100% last 10',
            [['Fouls/90', '1.5'], ['WC pedigree', '2022 semi-final'], ['YC/season', '7']],
            [1,1,1,1,1,1,1,1,1,1], 90,
            [{ label: 'Amrabat 1+ fouls', odds: ['-150 bet365', '-140 FanDuel'] }],
            'Morocco DM hero from WC22. 100% last 10 — fouls every game to protect the back line.'),
        ],
        shots: [
          shot('Hakim Ziyech', 'Galatasaray · Morocco · RW', false, 'h90', '90% last 10',
            [['Shots/90', '2.3'], ['SOT/game', '1.1'], ['Morocco MD2', 'Won 1-0 Scotland']],
            [1,1,1,1,1,0,1,1,1,1], [1,1,0,1,1,1,1,0,1,1], 82, 70,
            [{ label: 'Ziyech 1+ SOT', odds: ['-130 est.'] }]),
        ],
        easy: [
          easy('Goals', 'Morocco over 2.5 goals', '-140 est.', 81, true),
          easy('Fouls ★', 'Amrabat 1+ fouls', '-150 bet365', 90, true),
          easy('Corners', 'Morocco 7+ corners', '-135 est.', 78, true),
          easy('Throw-ins', 'Over 38 total throw-ins', '-115 est.', 80, true),
        ],
        parlay: [leg('Amrabat 1+ fouls', '-150'), leg('Morocco over 2.5 goals', '-140'), leg('Morocco 7+ corners', '-135')],
        parlayReturn: '+185–215',
        upsetNote: 'Haiti lost both MD1 and MD2. Morocco won MD2 1-0 Scotland. Only 10% upset risk.',
        ai: 'Morocco (-700, won MD2 1-0 Scotland) vs Haiti (lost both games). Amrabat: 1.5 fouls/90, 100% last 10. Ziyech: 2.3 shots/90.',
      },

      // ── GROUP A 9pm ET ───────────────────────────────────────
      {
        id: 'cze_mex', live: false, liveScore: null,
        teams: '🇨🇿 Czechia vs Mexico 🇲🇽',
        group: 'Group A', venue: 'Mexico City · Estadio Azteca', time: '9pm ET / 2am BST',
        tag: 'info', tagLabel: '56% Mexico (Azteca)',
        conf: 56, upset: 44,
        odds: { h: '+380', d: '+280', a: '-150', ou: '2.5' },
        homeTeam: 'Czechia', awayTeam: 'Mexico', winner: 'Mexico',
        wP: 16, dP: 28, aP: 56,
        keyPlayers: { home: ['Patrik Schick'], away: ['Hirving Lozano'] },
        confBars: [
          { label: 'Mexico win at Azteca (huge home advantage)', pct: 56, color: '#f59e0b' },
          { label: 'Schick 1+ SOT', pct: 67, color: '#3b82f6' },
          { label: 'BTTS both teams score', pct: 63, color: '#f59e0b' },
        ],
        fouls: [],
        shots: [
          shot('Patrik Schick', 'Leverkusen · Czechia · ST', false, 'h90', '90% last 10',
            [['Shots/90 BL', '2.9'], ['SOT/game', '1.4'], ['Must win', 'Yes — 3pts needed']],
            [1,1,1,1,1,0,1,1,1,1], [1,1,0,1,1,1,0,1,1,1], 83, 67,
            [{ label: 'Schick 1+ SOT', odds: ['-125 est.'] }]),
          shot('Hirving Lozano', 'PSV · Mexico · RW', false, 'h90', '90% last 10',
            [['Shots/90 Ere', '3.1'], ['SOT/game', '1.4'], ['Mexico MD2', 'Won 1-0 S.Korea']],
            [1,1,1,1,1,1,0,1,1,1], [1,1,0,1,1,1,1,0,1,1], 83, 67,
            [{ label: 'Lozano 1+ SOT', odds: ['-125 est.'] }]),
        ],
        easy: [
          easy('SOT prop', 'Schick 1+ SOT', '-125 est.', 67, false),
          easy('BTTS', 'Both teams score', '+100 est.', 63, false),
          easy('Throw-ins', 'Over 42 throw-ins', '-110 est.', 72, true),
          easy('Cards', 'Over 3.5 cards (Azteca tension)', '+140 est.', 61, false),
        ],
        parlay: [leg('Schick 1+ SOT', '-125'), leg('BTTS', '+100')],
        parlayReturn: '+120–145',
        upsetNote: '44% — Czechia need to beat Mexico at the Azteca (massive home advantage). BTTS and Schick SOT are safer than result.',
        ai: 'Mexico (-150, Azteca home, won both MD1+MD2) vs Czechia (+380, drew MD2 1-1 South Africa, must win). Schick: 2.9 shots/90.',
      },

      {
        id: 'saf_kor', live: false, liveScore: null,
        teams: '🇿🇦 South Africa vs South Korea 🇰🇷',
        group: 'Group A', venue: 'Monterrey · Estadio BBVA', time: '9pm ET / 2am BST',
        tag: 'info', tagLabel: '60% S.Korea',
        conf: 60, upset: 40,
        odds: { h: '+380', d: '+270', a: '-165', ou: '2.5' },
        homeTeam: 'South Africa', awayTeam: 'South Korea', winner: 'South Korea',
        wP: 18, dP: 22, aP: 60,
        keyPlayers: { home: [], away: ['Son Heung-min', 'Lee Jae-sung'] },
        confBars: [
          { label: 'South Korea win', pct: 60, color: '#f59e0b' },
          { label: 'Son Heung-min 1+ SOT', pct: 65, color: '#3b82f6' },
          { label: 'Under 2.5 goals (tight match)', pct: 58, color: '#f59e0b' },
        ],
        fouls: [
          foul('Lee Jae-sung', 'Mainz · South Korea · CM', false, 'h90', '90% last 10',
            [['Fouls/90', '1.2'], ['Role', 'Press CM'], ['YC/season', '5']],
            [1,1,1,1,1,0,1,1,1,1], 72,
            [{ label: 'Lee 1+ fouls', odds: ['-125 est.'] }],
            'South Korea pressing midfielder who fouls consistently. 90% last 10.'),
        ],
        shots: [
          shot('Son Heung-min', 'LAFC · South Korea · FW', false, 'h90', '90% last 10',
            [['Shots/90', '2.6'], ['SOT/game', '1.3'], ['WC26 goals', '0 (2 assists)']],
            [1,1,1,1,1,1,0,1,1,1], [1,1,0,1,1,1,1,0,1,1], 82, 65,
            [{ label: 'Son 1+ SOT', odds: ['-130 est.'] }]),
        ],
        easy: [
          easy('SOT prop', 'Son 1+ SOT', '-130 est.', 65, false),
          easy('Goals', 'Under 2.5 goals', '-110 est.', 58, false),
          easy('Throw-ins', 'Over 40 total throw-ins', '-110 est.', 70, true),
        ],
        parlay: [leg('Lee 1+ fouls', '-125'), leg('Son 1+ SOT', '-130')],
        parlayReturn: '+115–140',
        upsetNote: 'South Africa drew Czechia 1-1 in MD2. South Korea won both. 40% upset — Africa upsets common this tournament.',
        ai: 'South Korea (-165, won both MD1+MD2) vs South Africa (+380, drew MD2 1-1 Czechia). Son: 2.6 shots/90. Lee: 90% fouls L10.',
      },
    ],
  },

  '25': {
    title: 'Thursday 25 June 2026',
    sub: 'MD3 · Groups D E F · 6 matches · 3 simultaneous pairs',
    matches: [
      {
        id: 'ned_tun', live: false, liveScore: null,
        teams: '🇳🇱 Netherlands vs Tunisia 🇹🇳',
        group: 'Group F (sim: Japan vs Sweden)', venue: 'Kansas City · Arrowhead', time: '7pm ET / 12am BST',
        tag: 'top', tagLabel: '★ 76% · Depay hat-trick',
        conf: 76, upset: 12,
        odds: { h: '-400', d: '+500', a: '+750', ou: '2.5' },
        homeTeam: 'Netherlands', awayTeam: 'Tunisia', winner: 'Netherlands',
        wP: 76, dP: 15, aP: 9,
        keyPlayers: { home: ['Memphis Depay', 'Ryan Gravenberch', 'Frenkie de Jong'], away: [] },
        confBars: [
          { label: 'Netherlands win', pct: 76, color: '#00c896' },
          { label: 'Depay 2+ SOT (hat-trick MD2)', pct: 77, color: '#3b82f6' },
          { label: 'Gravenberch 1+ fouls (100% L10)', pct: 96, color: '#00c896' },
          { label: 'De Jong 1+ fouls (100% L10)', pct: 88, color: '#00c896' },
          { label: 'Netherlands 8+ corners', pct: 79, color: '#a855f7' },
          { label: 'Over 44 throw-ins', pct: 85, color: '#3b82f6' },
        ],
        fouls: [
          foul('Ryan Gravenberch', 'Liverpool · Netherlands · DM', true, 'h100', '100% last 10',
            [['Fouls/90 PL', '1.4'], ['MD2 vs Sweden', 'MOT · 5-1 win'], ['Rating MD1', '7.3 Sofascore']],
            [1,1,1,1,1,1,1,1,1,1], 96,
            [{ label: 'Gravenberch 1+ fouls', odds: ['-175 bet365', '-165 FanDuel'] }],
            '100% last 10 across PL and UCL. NED dominant after Depay hat-trick in 5-1 win vs Sweden.'),
          foul('Frenkie de Jong', 'Barcelona · Netherlands · CM', true, 'h100', '100% last 10',
            [['Fouls/90 LL', '0.61'], ['Fouls won/g', '1.1'], ['YC 25 LL games', '6']],
            [1,1,1,1,1,1,1,1,1,1], 88,
            [{ label: 'De Jong 1+ fouls', odds: ['-155 bet365', '-145 FanDuel'] }, { label: 'De Jong booked', odds: ['+185 Paddy'] }],
            '100% last 10. 6 bookings in 25 La Liga games. Card at +185 outstanding value.'),
        ],
        shots: [
          shot('Memphis Depay', 'Netherlands · ST · NL all-time top scorer', true, 'h100', '100% last 10',
            [['Shots/90', '3.2'], ['SOT/game', '1.6'], ['MD2 result', 'HAT-TRICK vs Sweden']],
            [1,1,1,1,1,1,1,1,1,1], [1,1,1,1,1,1,1,1,0,1], 96, 77,
            [{ label: 'Depay 2+ SOT', odds: ['-150 est.'] }, { label: 'Depay anytime scorer', odds: ['+120 est.'] }]),
        ],
        easy: [
          easy('Goals', 'Over 2.5 goals', '-130 est.', 74, true),
          easy('Fouls ★', 'Gravenberch 1+ fouls', '-175 bet365', 96, true),
          easy('SOT prop', 'Depay 2+ SOT', '-150 est.', 77, true),
          easy('Corners', 'Netherlands 8+ corners', '-130 est.', 79, true),
          easy('Throw-ins', 'Over 44 total throw-ins', '-115 est.', 85, true),
          easy('Shots', 'Netherlands over 16 shots', '-130 est.', 80, true),
        ],
        parlay: [leg('Gravenberch 1+ fouls', '-175'), leg('De Jong 1+ fouls', '-155'), leg('Depay 2+ SOT', '-150'), leg('Over 2.5 goals', '-130')],
        parlayReturn: '+205–250',
        upsetNote: 'Tunisia lost 1-5 Sweden MD1, lost 0-4 Japan MD2. Only 12% upset risk.',
        refNote: '📋 Tunisia defensively fragile vs elite wingers. NED avg 9+ corners in dominant wins.',
        ai: 'Netherlands (-400, won MD2 5-1 Sweden Depay hat-trick) vs Tunisia (lost MD1 1-5, lost MD2 0-4 Japan). Depay: 3.2 shots/90. Gravenberch: 100% fouls L10. De Jong: 100% fouls L10.',
      },

      {
        id: 'jap_swe', live: false, liveScore: null,
        teams: '🇯🇵 Japan vs Sweden 🇸🇪',
        group: 'Group F (sim: Netherlands vs Tunisia)', venue: 'Dallas · AT&T Stadium', time: '7pm ET / 12am BST',
        tag: 'upset', tagLabel: '⚠ Sweden 58% · Japan 42%',
        conf: 58, upset: 42,
        odds: { h: '+230', d: '+240', a: '-150', ou: '2.5' },
        homeTeam: 'Japan', awayTeam: 'Sweden', winner: 'Sweden',
        wP: 42, dP: 27, aP: 58,
        keyPlayers: { home: ['Wataru Endo', 'Takefusa Kubo'], away: ['Alexander Isak', 'Viktor Gyökeres'] },
        confBars: [
          { label: 'Sweden win', pct: 58, color: '#f59e0b' },
          { label: 'Isak 2+ SOT', pct: 72, color: '#3b82f6' },
          { label: 'Gyökeres 1+ fouls (100% L10)', pct: 91, color: '#00c896' },
          { label: 'Endo 1+ fouls (Japan DM)', pct: 82, color: '#00c896' },
          { label: 'Japan upset risk (beat Germany WC22)', pct: 42, color: '#ef4444' },
        ],
        fouls: [
          foul('Viktor Gyökeres', 'Arsenal · Sweden · ST', true, 'h100', '100% last 10',
            [['Fouls/90 PL', '1.41'], ['Fouls drawn/season', '31'], ['YC PL 25/26', '5']],
            [1,1,1,1,1,1,1,1,1,1], 91,
            [{ label: 'Gyökeres 1+ fouls', odds: ['-165 est. bet365', '-155 est. FanDuel'] }],
            'Physical Arsenal striker — commits fouls every match via aggressive hold-up play. 100% last 10.'),
          foul('Wataru Endo', 'Liverpool · Japan · DM · Captain', true, 'h90', '90% last 10',
            [['Fouls/90 PL', '1.3'], ['Role', 'Anchor DM vs SWE'], ['YC PL', '6']],
            [1,1,1,1,1,1,1,1,1,0], 82,
            [{ label: 'Endo 1+ fouls', odds: ['-145 est. bet365'] }],
            'Japan captain DM breaks Swedish transitions. 82% last 10.'),
        ],
        shots: [
          shot('Alexander Isak', 'Liverpool · Sweden · ST · career-best', true, 'h100', '100% last 10',
            [['Shots/90 PL', '3.1'], ['SOT/game', '1.5'], ['PL goals 25/26', '24']],
            [1,1,1,1,1,1,1,1,1,1], [1,1,1,1,0,1,1,1,1,1], 96, 72,
            [{ label: 'Isak 2+ SOT', odds: ['-135 est.'] }, { label: 'Isak anytime scorer', odds: ['+130 est.'] }]),
          shot('Takefusa Kubo (replaces Mitoma)', 'Real Sociedad · Japan · RW · Mitoma INJURED OUT', false, 'h80', '80% last 10',
            [['Shots/90 LL', '2.3'], ['SOT/game', '1.1'], ['Mitoma status', 'INJURED — OUT']],
            [1,1,1,0,1,1,1,0,1,1], [1,1,0,1,1,0,1,1,0,1], 76, 64,
            [{ label: 'Kubo 1+ SOT', odds: ['-120 est.'] }]),
        ],
        easy: [
          easy('SOT prop ★', 'Isak 2+ SOT', '-135 est.', 72, true),
          easy('Fouls', 'Gyökeres 1+ fouls (100% L10)', '-165 est.', 91, true),
          easy('BTTS', 'Both teams score', '+105 est.', 65, false),
          easy('Throw-ins', 'Over 44 throw-ins', '-110 est.', 77, true),
        ],
        parlay: [leg('Gyökeres 1+ fouls', '-165'), leg('Endo 1+ fouls', '-145'), leg('Isak 2+ SOT', '-135')],
        parlayReturn: '+185–215',
        upsetNote: 'Japan beat Germany WC22 (+1500), beat Tunisia 4-0 MD2. Mitoma INJURED OUT. 42% upset. Isak SOT props safer than Sweden result.',
        ai: 'Japan (Mitoma OUT, Kubo replaces) vs Sweden (lost MD2 0-5 Netherlands). Isak: 3.1 shots/90, 24 PL goals. Gyökeres: 1.41 fouls/90, 100% last 10.',
      },

      {
        id: 'usa_tur', live: false, liveScore: null,
        teams: '🇺🇸 USA vs Türkiye 🇹🇷',
        group: 'Group D (sim: Paraguay vs Australia)', venue: 'Los Angeles · SoFi Stadium', time: '10pm ET / 3am BST',
        tag: 'upset', tagLabel: '⚠ USA 61% · Turkey revenge',
        conf: 61, upset: 39,
        odds: { h: '-135', d: '+280', a: '+340', ou: '2.5' },
        homeTeam: 'USA', awayTeam: 'Türkiye', winner: 'USA',
        wP: 61, dP: 25, aP: 39,
        keyPlayers: { home: ['Christian Pulisic'], away: ['İsmail Yüksek', 'Arda Güler'] },
        confBars: [
          { label: 'USA win (already qualified)', pct: 61, color: '#f59e0b' },
          { label: 'Türkiye upset (lost MD1+MD2)', pct: 39, color: '#ef4444' },
          { label: 'Yüksek 1+ fouls (100% L10)', pct: 93, color: '#00c896' },
          { label: 'Güler 1+ SOT (desperation game)', pct: 70, color: '#3b82f6' },
        ],
        fouls: [
          foul('İsmail Yüksek', 'Fenerbahçe · Türkiye · DM', true, 'h100', '100% last 10',
            [['Fouls/90 WC qual', '2.0'], ['Fouls Eur. League', '1.1/g'], ['YC qualifying', '3 in 6']],
            [1,1,1,1,1,1,1,1,1,1], 93,
            [{ label: 'Yüksek 1+ fouls', odds: ['-175 bet365', '-160 FanDuel'] }, { label: 'Yüksek booked', odds: ['+165 Paddy'] }],
            '2.0 fouls/90 in WC qualifying, 100% last 10. Elimination game elevates aggression further.'),
        ],
        shots: [
          shot('Arda Güler', 'Real Madrid · Türkiye · AM', false, 'h80', '80% last 10',
            [['Shots/90 LL', '2.2'], ['Fouls drawn/g', '2.4'], ['Must win', 'Career-defining']],
            [1,1,1,1,0,1,1,0,1,1], [1,1,0,1,1,0,1,1,1,1], 76, 70,
            [{ label: 'Güler 1+ SOT', odds: ['-140 est.'] }]),
          shot('Christian Pulisic', 'AC Milan · USA · CAM', false, 'h90', '90% last 10',
            [['Shots/90 SA', '2.4'], ['MD1+MD2', '3 goal involvements'], ['USA status', 'Already qualified']],
            [1,1,1,1,1,1,0,1,1,1], [1,1,0,1,1,1,1,0,1,1], 82, 68,
            [{ label: 'Pulisic 1+ SOT', odds: ['-130 est.'] }]),
        ],
        easy: [
          easy('Fouls ★', 'Yüksek 1+ fouls (100% L10)', '-175 bet365', 93, true),
          easy('Goals', 'Over 2.5 goals (Turkey attack freely)', '+110 est.', 62, false),
          easy('Cards', 'Over 3.5 total cards', '+140 est.', 63, false),
          easy('Throw-ins', 'Over 42 throw-ins', '-110 est.', 74, true),
        ],
        parlay: [leg('Yüksek 1+ fouls', '-175'), leg('Güler 1+ SOT', '-140'), leg('Over 3.5 cards', '+140')],
        parlayReturn: '+175–210',
        upsetNote: 'Turkey lost both MD1 and MD2 — nothing to lose, all-out attack. USA may rotate with qualification secured. 39% upset.',
        ai: 'USA (-135, already qualified) vs Türkiye (+340, lost MD1+MD2, elimination game). Yüksek DM: 2.0 fouls/90, 100% last 10. Güler: 2.2 shots/90.',
      },
    ],
  },

  '26': {
    title: 'Friday 26 June 2026',
    sub: 'MD3 · Groups G H I · 6 matches · simultaneous pairs',
    matches: [
      {
        id: 'nor_fra', live: false, liveScore: null,
        teams: '🇳🇴 Norway vs France 🇫🇷',
        group: 'Group I (sim: Senegal vs Iraq)', venue: 'Boston · Gillette Stadium', time: '3pm ET / 8pm BST',
        tag: 'top', tagLabel: '★ Haaland vs Mbappé',
        conf: 62, upset: 38,
        odds: { h: '+127', d: '+225', a: '-333', ou: '2.5' },
        homeTeam: 'Norway', awayTeam: 'France', winner: 'France',
        wP: 38, dP: 20, aP: 42,
        keyPlayers: { home: ['Erling Haaland'], away: ['Kylian Mbappé', 'Aurélien Tchouaméni'] },
        confBars: [
          { label: 'France win vs Norway', pct: 62, color: '#f59e0b' },
          { label: 'Haaland 2+ SOT (backs regardless of result)', pct: 80, color: '#3b82f6' },
          { label: 'Mbappé 2+ SOT', pct: 78, color: '#3b82f6' },
          { label: 'Tchouaméni 1+ fouls (100% L10)', pct: 94, color: '#00c896' },
        ],
        fouls: [
          foul('Aurélien Tchouaméni', 'Real Madrid · France · DM', true, 'h100', '100% last 10',
            [['Fouls/90 LL', '1.6'], ['Intl fouls (NL)', '1.4/g'], ['YC season', '5+']],
            [1,1,1,1,1,1,1,1,1,1], 94,
            [{ label: 'Tchouaméni 1+ fouls', odds: ['-165 bet365', '-155 FanDuel'] }],
            '100% last 10 across La Liga and Nations League. France anchor DM commits fouls structurally vs every opponent.'),
        ],
        shots: [
          shot('Erling Haaland', 'Man City · Norway · ST', true, 'h100', '100% last 10',
            [['SOT/game PL', '2.2'], ['WC26 goals', '4 (vs Iraq + Senegal)'], ['WC qualifying', 'Top scorer']],
            [1,1,1,1,1,1,1,1,1,1], [1,1,1,1,1,1,0,1,1,1], 97, 80,
            [{ label: 'Haaland 2+ SOT', odds: ['-160 est.'] }, { label: 'Haaland anytime scorer', odds: ['-175 est.'] }]),
          shot('Kylian Mbappé', 'Real Madrid · France · ST · France all-time top scorer', true, 'h100', '100% last 10',
            [['Shots/90 LL', '3.79'], ['WC26 goals', '4 (vs Senegal + Iraq)'], ['Golden Boot race', 'Leading']],
            [1,1,1,1,1,1,1,1,1,1], [1,1,1,1,1,1,1,0,1,1], 97, 78,
            [{ label: 'Mbappé 2+ SOT', odds: ['-145 est.'] }, { label: 'Mbappé anytime scorer', odds: ['-140 est.'] }]),
        ],
        easy: [
          easy('SOT duel ★', 'Haaland 2+ SOT (safe regardless of result)', '-160 est.', 80, true),
          easy('SOT prop', 'Mbappé 2+ SOT', '-145 est.', 78, true),
          easy('Fouls ★', 'Tchouaméni 1+ fouls', '-165 bet365', 94, true),
          easy('Goals', 'Norway vs France over 2.5', '+105 est.', 65, false),
        ],
        parlay: [leg('Haaland 2+ SOT', '-160'), leg('Mbappé 2+ SOT', '-145'), leg('Tchouaméni 1+ fouls', '-165')],
        parlayReturn: '+195–230',
        upsetNote: 'Norway are +127 — near evens vs France. 38% upset risk. Back SOT props over the result.',
        ai: 'Norway (+127, won MD1+MD2, Haaland 4 WC goals) vs France (-333, won MD1+MD2, Mbappé 4 WC goals). Both qualified. Haaland: 2.2 SOT/game. Mbappé: 3.79 shots/90. Tchouaméni: 100% fouls L10.',
      },
    ],
  },

  '27': {
    title: 'Saturday 27 June 2026',
    sub: 'MD3 · Groups J K L · 6 matches · simultaneous pairs',
    matches: [
      {
        id: 'eng_pan', live: false, liveScore: null,
        teams: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England vs Panama 🇵🇦',
        group: 'Group L (sim: Croatia vs Ghana)', venue: 'New Jersey · MetLife Stadium', time: '5pm ET / 10pm BST',
        tag: 'top', tagLabel: '★ 85% England',
        conf: 85, upset: 10,
        odds: { h: '-600', d: '+650', a: '+1400', ou: '2.5' },
        homeTeam: 'England', awayTeam: 'Panama', winner: 'England',
        wP: 85, dP: 9, aP: 6,
        keyPlayers: { home: ['Harry Kane', 'Declan Rice'], away: [] },
        confBars: [
          { label: 'England win', pct: 85, color: '#00c896' },
          { label: 'Kane 2+ SOT', pct: 80, color: '#3b82f6' },
          { label: 'Rice 1+ fouls (100% L10)', pct: 96, color: '#00c896' },
          { label: 'England over 3 goals', pct: 74, color: '#00c896' },
          { label: 'England 8+ corners', pct: 79, color: '#a855f7' },
        ],
        fouls: [
          foul('Declan Rice', 'Arsenal · England · DM', true, 'h100', '100% last 10',
            [['Fouls/90 PL', '1.8'], ['YC PL+UCL', '9'], ['vs Panama press', 'Near certainty']],
            [1,1,1,1,1,1,1,1,1,1], 96,
            [{ label: 'Rice 1+ fouls committed', odds: ['-165 bet365', '-155 FanDuel'] }, { label: 'Rice to be booked', odds: ['+195 bet365'] }],
            '1.8 fouls/90 in PL. 10/10 last matches. England DM vs Panama = near certainty.'),
        ],
        shots: [
          shot('Harry Kane', 'Bayern Munich · England · ST', true, 'h100', '100% last 10',
            [['Shots/90 BL', '4.5'], ['SOT/game', '2.16'], ['BL goals 25/26', '36']],
            [1,1,1,1,1,1,1,1,1,1], [1,1,1,1,1,1,1,1,0,1], 96, 80,
            [{ label: 'Kane 2+ SOT', odds: ['-145 bet365'] }, { label: 'Kane anytime scorer', odds: ['EV FanDuel'] }]),
        ],
        easy: [
          easy('Fouls ★', 'Rice 1+ fouls (100% L10)', '-165 bet365', 96, true),
          easy('SOT prop', 'Kane 2+ SOT', '-145 bet365', 80, true),
          easy('Goals', 'England over 3 goals', '+115 est.', 74, true),
          easy('Corners', 'England 8+ corners', '-130 est.', 79, true),
          easy('Throw-ins', 'Over 44 total throw-ins', '-115 est.', 80, true),
        ],
        parlay: [leg('Rice 1+ fouls', '-165'), leg('Kane 2+ SOT', '-145'), leg('England over 3 goals', '+115'), leg('England 8+ corners', '-130')],
        parlayReturn: '+200–240',
        upsetNote: 'Panama lost both MD1+MD2. England won both. 10% upset risk — best Saturday banker.',
        ai: 'England (-600, won MD1 4-2 Croatia, drew MD2 0-0 Ghana) vs Panama (lost both). Kane: 4.5 shots/90. Rice: 1.8 fouls/90, 100% last 10.',
      },
    ],
  },
};
